[package]
name = "proxy-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "http_proxy"
crate-type = ["staticlib", "cdylib"]

[dependencies]
proxy-core = { path = "../proxy-core" }
proxy-client = { path = "../proxy-client" }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }

[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "linux"))'.dependencies]
sysproxy = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2"

[features]
mac-app-store = ["proxy-client/network-extension", "proxy-core/no-external-geo"]
