//! Crash-safe restore point for the macOS network settings TUN mode changes.
//!
//! Enabling TUN repoints the primary service's DNS and `/etc/resolv.conf` at the
//! tunnel gateway. Ordinary teardown puts both back, and losing the control
//! socket makes the helper do the same, so the ordinary paths are covered.
//!
//! What is not covered is the helper dying without running any code: `kill -9`,
//! a panic in a signal-unsafe place, or power loss. The machine is then left
//! resolving through a gateway that no longer exists, which looks exactly like
//! "the network is broken" to the user and cannot be repaired by restarting the
//! application, because nothing remembers what the settings used to be.
//!
//! So the previous values are written to disk before they are changed, and any
//! record found at startup is applied and deleted. This mirrors
//! [`crate::cli_config`]'s system-proxy restore point, which solves the same
//! problem for the same reason.
//!
//! The record lives beside the helper's other state rather than in a shared
//! temporary directory: it is replayed by a root process, so a file any local
//! user could write would be an escalation vector.

use std::io;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// File name inside the helper's state directory.
const RECORD_FILE: &str = "dns-restore.json";

/// `/etc/resolv.conf` is generated by macOS from the service configuration, but
/// TUN setup overwrites it directly, so its previous contents are recorded too.
const RESOLV_CONF: &str = "/etc/resolv.conf";

/// What the primary network service's DNS looked like before TUN setup.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DnsRestorePoint {
    /// `SCDynamicStore` service identifier the DNS override was applied to.
    pub service_id: String,
    /// Friendly service name, as `networksetup` expects it (e.g. `Wi-Fi`).
    pub service_name: Option<String>,
    /// Resolvers configured before TUN setup. `None` means the service had no
    /// override at all and DNS came from DHCP, which must be restored by
    /// *clearing* the override rather than writing values back.
    pub servers: Option<Vec<String>>,
    /// Previous `/etc/resolv.conf` bytes, when it could be read.
    pub resolv_conf: Option<Vec<u8>>,
}

impl DnsRestorePoint {
    fn path(state_dir: &Path) -> PathBuf {
        state_dir.join(RECORD_FILE)
    }

    /// Persist this record so a helper that dies without unwinding can still be
    /// recovered from on the next run.
    pub fn store(&self, state_dir: &Path) -> io::Result<()> {
        std::fs::create_dir_all(state_dir)?;
        let path = Self::path(state_dir);
        let encoded = serde_json::to_vec(self).map_err(io::Error::other)?;
        std::fs::write(&path, encoded)?;
        // Root writes this and root replays it; keep it unreadable to others so
        // the values cannot be tampered with between runs.
        let permissions = std::os::unix::fs::PermissionsExt::from_mode(0o600);
        let _ = std::fs::set_permissions(&path, permissions);
        Ok(())
    }

    /// Remove a stored record, after a successful restore or a clean teardown.
    pub fn discard(state_dir: &Path) {
        let _ = std::fs::remove_file(Self::path(state_dir));
    }

    /// Read and delete any stored record.
    ///
    /// Deleting first is deliberate: a record that cannot be applied must not be
    /// retried on every subsequent launch.
    pub fn take(state_dir: &Path) -> Option<Self> {
        let path = Self::path(state_dir);
        let contents = std::fs::read(&path).ok()?;
        let _ = std::fs::remove_file(&path);
        match serde_json::from_slice(&contents) {
            Ok(record) => Some(record),
            Err(error) => {
                log::warn!("ignoring a damaged DNS restore point: {error}");
                None
            }
        }
    }

    /// Capture the current DNS configuration of the primary network service.
    ///
    /// Returns `None` when the primary service cannot be determined, or when the
    /// live configuration is already a tunnel resolver. Recording the latter
    /// would be worse than recording nothing: a "restore" to the tunnel gateway
    /// leaves the user exactly as broken, while an absent record at least lets a
    /// later clean teardown or a manual DHCP reset take effect.
    ///
    /// This is reachable in practice — a previous session that failed to restore,
    /// or another VPN owning the resolver — so it is a real case, not a
    /// theoretical one.
    pub fn capture() -> Option<Self> {
        let service_id = primary_service_id()?;
        let service_name = primary_service_name();
        let servers = configured_dns_servers(service_name.as_deref());
        if let Some(servers) = &servers
            && servers.iter().any(|server| is_tunnel_resolver(server))
        {
            log::warn!(
                "not recording a DNS restore point: the live resolvers {servers:?} are already a \
                 tunnel gateway"
            );
            return None;
        }
        let resolv_conf = std::fs::read(RESOLV_CONF).ok();
        Some(Self {
            service_id,
            service_name,
            servers,
            resolv_conf,
        })
    }

    /// Whether this record still describes the live configuration.
    ///
    /// Used to skip a restore when something else already put DNS back, so a
    /// leftover record cannot overwrite newer settings.
    pub fn differs_from_current(&self) -> bool {
        configured_dns_servers(self.service_name.as_deref()) != self.servers
    }

    /// Put the recorded configuration back.
    pub fn apply(&self) -> io::Result<()> {
        let Some(service_name) = self.service_name.as_deref() else {
            return Err(io::Error::other(
                "the recorded network service has no name; DNS cannot be restored through \
                 networksetup",
            ));
        };

        // `networksetup` needs the literal "Empty" to clear an override, which is
        // how a DHCP-provided resolver is put back.
        let mut arguments = vec!["-setdnsservers", service_name];
        match &self.servers {
            Some(servers) if !servers.is_empty() => {
                arguments.extend(servers.iter().map(String::as_str));
            }
            _ => arguments.push("Empty"),
        }
        run_networksetup(&arguments)?;

        if let Some(contents) = &self.resolv_conf {
            // Best effort: macOS regenerates this file, so a failure here is not
            // worth failing the whole restore over.
            if let Err(error) = std::fs::write(RESOLV_CONF, contents) {
                log::warn!("could not restore {RESOLV_CONF}: {error}");
            }
        }
        Ok(())
    }
}

/// Apply and clear a restore point left behind by a helper that never unwound.
///
/// Returns `true` when a record was found and applied.
pub fn restore_orphaned_dns(state_dir: &Path) -> bool {
    let Some(record) = DnsRestorePoint::take(state_dir) else {
        return false;
    };
    if !record.differs_from_current() {
        log::info!("a DNS restore point was left behind but the live settings already match it");
        return false;
    }
    match record.apply() {
        Ok(()) => {
            log::info!(
                "restored DNS settings left behind by a previous TUN session on `{}`",
                record.service_name.as_deref().unwrap_or(&record.service_id)
            );
            flush_dns_cache();
            true
        }
        Err(error) => {
            log::error!(
                "could not restore the DNS settings left by a previous TUN session: {error}"
            );
            false
        }
    }
}

/// The TUN subnet `tproxy-config` assigns, as its first three octets.
///
/// Mirrors `tproxy_config::TUN_IPV4` (`10.0.0.33`) and `TUN_GATEWAY`
/// (`10.0.0.1`). Duplicated rather than depended upon: this crate does not link
/// `tproxy-config`, and pulling it in for two constants is not worth it. The
/// values are part of that crate's public API and have been stable across it.
const TUN_SUBNET_PREFIX: [u8; 3] = [10, 0, 0];

/// Whether `server` is the TUN gateway rather than a real resolver.
///
/// Anything inside the tunnel's own subnet counts: the gateway is what TUN setup
/// installs, and a resolver there is only reachable while the tunnel is up.
fn is_tunnel_resolver(server: &str) -> bool {
    match server.parse::<std::net::IpAddr>() {
        Ok(std::net::IpAddr::V4(address)) => address.octets()[..3] == TUN_SUBNET_PREFIX,
        _ => false,
    }
}

/// Primary service UUID from the dynamic store.
fn primary_service_id() -> Option<String> {
    let dictionary = query_scutil("show State:/Network/Global/IPv4")?;
    scutil_field(&dictionary, "PrimaryService")
}

/// Friendly name of the primary service, as `networksetup` refers to it.
fn primary_service_name() -> Option<String> {
    let interface = query_scutil("show State:/Network/Global/IPv4")
        .and_then(|dictionary| scutil_field(&dictionary, "PrimaryInterface"))?;
    // Map the BSD device (en0) to the service name (Wi-Fi).
    let listing = run_capture("networksetup", &["-listnetworkserviceorder"])?;
    let mut current_service = None;
    for line in listing.lines() {
        if let Some(rest) = line.split_once(") ").map(|(_, rest)| rest) {
            current_service = Some(rest.trim().to_string());
        }
        if line.contains(&format!("Device: {interface})")) {
            return current_service;
        }
    }
    None
}

/// Resolvers currently overridden on `service_name`, or `None` when it uses DHCP.
fn configured_dns_servers(service_name: Option<&str>) -> Option<Vec<String>> {
    let service_name = service_name?;
    let output = run_capture("networksetup", &["-getdnsservers", service_name])?;
    // The command reports a sentence rather than an empty list when unset.
    if output.contains("aren't any DNS Servers set") {
        return None;
    }
    let servers = output
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && line.parse::<std::net::IpAddr>().is_ok())
        .map(ToString::to_string)
        .collect::<Vec<_>>();
    (!servers.is_empty()).then_some(servers)
}

fn run_networksetup(arguments: &[&str]) -> io::Result<()> {
    let output = std::process::Command::new("networksetup")
        .args(arguments)
        .output()?;
    if output.status.success() {
        return Ok(());
    }
    let detail = String::from_utf8_lossy(if output.stderr.is_empty() {
        &output.stdout
    } else {
        &output.stderr
    });
    Err(io::Error::other(format!(
        "networksetup {} failed: {}",
        arguments.join(" "),
        detail.trim()
    )))
}

fn run_capture(program: &str, arguments: &[&str]) -> Option<String> {
    let output = std::process::Command::new(program)
        .args(arguments)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Run one `scutil` query by feeding it on stdin.
fn query_scutil(query: &str) -> Option<String> {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let mut child = Command::new("scutil")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .ok()?;
    child
        .stdin
        .as_mut()?
        .write_all(format!("{query}\n").as_bytes())
        .ok()?;
    let output = child.wait_with_output().ok()?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Pull `key : value` out of `scutil` dictionary output.
fn scutil_field(dictionary: &str, key: &str) -> Option<String> {
    dictionary.lines().find_map(|line| {
        let (name, value) = line.split_once(':')?;
        (name.trim() == key).then(|| value.trim().to_string())
    })
}

fn flush_dns_cache() {
    let _ = std::process::Command::new("dscacheutil")
        .arg("-flushcache")
        .status();
    let _ = std::process::Command::new("killall")
        .args(["-HUP", "mDNSResponder"])
        .status();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> DnsRestorePoint {
        DnsRestorePoint {
            service_id: "26103486-53AE-4C2A-94E8-BFFA741C1326".to_string(),
            service_name: Some("Wi-Fi".to_string()),
            servers: Some(vec!["192.168.1.1".to_string()]),
            resolv_conf: Some(b"nameserver 192.168.1.1\n".to_vec()),
        }
    }

    /// A record that cannot be applied must not be retried forever, so `take`
    /// removes the file before the caller gets a chance to fail.
    #[test]
    fn a_record_is_removed_when_it_is_read() {
        let dir = std::env::temp_dir().join(format!("dns-restore-test-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        assert!(DnsRestorePoint::take(&dir).is_none(), "nothing stored yet");

        sample().store(&dir).unwrap();
        assert!(DnsRestorePoint::path(&dir).exists());

        assert_eq!(DnsRestorePoint::take(&dir), Some(sample()));
        assert!(
            !DnsRestorePoint::path(&dir).exists(),
            "reading must consume the record"
        );
        assert!(DnsRestorePoint::take(&dir).is_none());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_damaged_record_is_discarded_rather_than_replayed() {
        let dir = std::env::temp_dir().join(format!("dns-restore-bad-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(DnsRestorePoint::path(&dir), b"{ not json").unwrap();

        assert!(DnsRestorePoint::take(&dir).is_none());
        assert!(!DnsRestorePoint::path(&dir).exists());

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn discard_is_safe_when_nothing_was_stored() {
        let dir = std::env::temp_dir().join(format!("dns-restore-empty-{}", std::process::id()));
        DnsRestorePoint::discard(&dir);
        sample().store(&dir).unwrap();
        DnsRestorePoint::discard(&dir);
        assert!(!DnsRestorePoint::path(&dir).exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A tunnel gateway must never be recorded as the value to restore, or the
    /// "recovery" would reinstate the broken state.
    #[test]
    fn tunnel_resolvers_are_recognized() {
        assert!(is_tunnel_resolver("10.0.0.1"), "the TUN gateway");
        assert!(is_tunnel_resolver("10.0.0.33"), "the TUN interface address");
        assert!(
            is_tunnel_resolver("10.0.0.53"),
            "anything in the TUN subnet"
        );
        assert!(!is_tunnel_resolver("192.168.1.1"));
        assert!(!is_tunnel_resolver("8.8.8.8"));
        assert!(
            !is_tunnel_resolver("10.1.0.1"),
            "a different 10/8 subnet is a real resolver"
        );
        assert!(!is_tunnel_resolver("not-an-address"));
    }

    /// The live capture must describe this machine, so a restore can act on it.
    /// Read-only: nothing here changes DNS.
    #[test]
    fn capture_describes_the_primary_service() {
        let Some(captured) = DnsRestorePoint::capture() else {
            // Either no primary service, or DNS is currently a tunnel gateway —
            // both are refusals by design, so there is nothing to assert.
            return;
        };
        assert!(!captured.service_id.is_empty());
        // A machine with a primary service reachable by name is the normal case;
        // without a name a restore cannot run, so assert we captured one.
        assert!(
            captured.service_name.is_some(),
            "expected a networksetup service name for the primary interface"
        );
        // Whatever is configured now must compare equal to itself.
        assert!(!captured.differs_from_current());
        // And it must never be the thing we are protecting against.
        if let Some(servers) = &captured.servers {
            assert!(!servers.iter().any(|server| is_tunnel_resolver(server)));
        }
    }
}
