name: cargo-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Build cli release
      run: cargo build --bin http-proxy-cli --features="cli-dep" --release --verbose
    - name: Build client release
      run: cargo build --bin http-proxy-client --release --verbose
    - name: Build server release
      run: cargo build --bin http-proxy-server --release --verbose