name: cargo-clippy-test

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2026-01-26
          components: clippy, rustfmt
      - name: cargo fmt
        run: cargo fmt -p proxy-core -p proxy-client -p proxy-server -p proxy-tui -p proxy-ffi -- --check
      - name: cargo clippy
        run: cargo clippy --workspace
      - name: cargo test
        run: cargo test --workspace
      - name: integration test
        if: matrix.os == 'ubuntu-latest'
        run: scripts/integration-test.sh
      - name: cargo build
        run: cargo build --workspace --release
